#include "SystemRat.h"

#include "WMIParser.h"

std::unordered_map<std::string, std::unordered_map<std::string, std::list<std::string>>> globalMap =
{
	{
		"Operating System",
{
	{
		"Win32_OperatingSystem",
{
	"Name",
	"BuildNumber",
	"BuildType",
	"CountryCode",
	"CurrentTimeZone",
	"Description",
	"FreePhysicalMemory",
	"FreeSpaceInPagingFiles",
	"FreeVirtualMemory",
	"InstallDate",
	"Manufacturer",
	"MaxNumberOfProcesses",
	"MaxProcessMemorySize",
	"NumberOfLicensedUsers",
	"NumberOfProcesses",
	"NumberOfUsers",
	"Organization",
	"SerialNumber",
	"ServicePackMajorVersion",
	"ServicePackMinorVersion",
	"Status",
	"SystemDevice",
	"SystemDirectory",
	"SystemDrive",
	"TotalVirtualMemorySize",
	"TotalVisibleMemorySize",
	"WindowsDirectory",
	"Version"
}
	},
			{
				"Win32_ComputerSystem",
{
	"Name",
	"AdminPasswordStatus",
	"BootupState",
	"Caption",
	"CreationClassName",
	"DNSHostName",
	"Domain",
	"LastLoadInfo",
	"Manufacturer",
	"Model",
	"NetworkServerModeEnabled",
	"NumberOfLogicalProcessors",
	"NumberOfProcessors",
	"PowerManagementSupported",
	"PrimaryOwnerName",
	"SystemFamily",
	"UserName",
	"WakeUpType",
	"Workgroup"
}
			},
			{
				"Win32_NetworkClient",
{
	"Name",
	"Manufacturer",
	"Status",
	"InstallDate",
	"Description",
	"Caption"
}
			},
			{
				"Win32_NetworkConnection",
{
	"Name",
	"UserName",
	"ResourceType",
	"ProviderName",
	"RemoteName",
	"RemotePath",
	"LocalName",
	"ConnectionType",
	"ConnectionState",
	"AccessMask",
	"InstallDate",
	"Description",
	"Caption",
	"Status"
}
			},
			{
				"Win32_Registry",
{
	"Name",
	"Description",
	"CurrentSize",
	"MaximumSize",
	"InstallDate",
	"Status"
}
			},
			{
				"Win32_UserAccount",
{
	"Name",
	"FullName",
	"AccountType",
	"Description",
	"LocalAccount",
	"InstallDate",
	"Status",
	"SID",
	"PasswordRequired",
	"PasswordChangeable",
	"PasswordExpires",
	"Lockout"
}
			},
			{
				"Win32_WindowsProductActivation",
{
	"ProductID",
	"Description",
	"IsNotificationOn",
	"RemainingEvaluationPeriod",
	"ServerName",
	"RemainingGracePeriod",
	"ActivationRequired"
}
			}
}
	},
	{
		"Hardware",
{
	{
		"Win32_Refrigeration",
{
	"Name",
	"InstallDate",
	"PowerManagementSupported",
	"DeviceID",
	"Availability",
	"ActiveCooling",
	"ConfigManagerErrorCode"
}
	},
			{
				"Win32_Keyboard",
{
	"Name",
	"PowerManagementSupported",
	"Password",
	"NumberOfFunctionKeys",
	"Layout",
	"IsLocked",
	"LastErrorCode",
	"InstallDate",
	"ErrorDescription",
	"DeviceID",
	"Description",
	"Availability"
}
			},
			{
				"Win32_PointingDevice",
{
	"Name",
	"Manufacturer",
	"NumberOfButtons",
	"DeviceID",
	"Handedness",
	"HardwareType",
	"IsLocked",
	"InstallDate",
	"PowerManagementSupported",
	"Resolution",
	"Availability",
	"ConfigManagerErrorCode",
	"ErrorDescription"
}
			},
			{
				"Win32_DiskDrive",
{
	"Name",
	"Model",
	"Manufacturer",
	"Availability",
	"Description",
	"DeviceID",
	"NeedsCleaning",
	"MaxBlockSize",
	"MediaLoaded",
	"SerialNumber",
	"Signature",
	"Size",
	"TotalCylinders",
	"TotalHeads",
	"TotalSectors",
	"MediaType",
	"Index",
	"CompressionMethod",
	"BytesPerSector",
	"LastErrorCode",
	"ErrorDescription",
	"Description"
}
			},
			{
				"Win32_BaseBoard",
{
	"Name",
	"Model",
	"Manufacturer",
	"InstallDate",
	"Weight",
	"Width",
	"Status",
	"SpecialRequirements",
	"SlotLayout",
	"SerialNumber",
	"RequiresDaughterBoard",
	"RequirementsDescription",
	"Removable",
	"Replaceable",
	"Product",
	"PoweredOn",
	"PartNumber",
	"Height",
	"Description",
	"Depth",
	"HostingBoard"
}
			},
			{
				"Win32_BIOS",
{
	"Name",
	"Manufacturer",
	"PrimaryBIOS",
	"SerialNumber",
	"LanguageEdition",
	"InstallDate",
	"EmbeddedControllerMinorVersion",
	"EmbeddedControllerMajorVersion",
	"Description",
	"CurrentLanguage",
	"CodeSet",
	"BuildNumber",
	"SoftwareElementID",
	"SystemBiosMajorVersion",
	"SystemBiosMinorVersion",
	"TargetOperatingSystem",
	"Version"
}
			},
			{
				"Win32_Processor",
{
	"Name",
	"Manufacturer",
	"MaxClockSpeed",
	"LoadPercentage",
	"Level",
	"NumberOfCores",
	"NumberOfEnabledCore",
	"NumberOfLogicalProcessors",
	"PartNumber",
	"PowerManagementSupported",
	"ProcessorId",
	"ProcessorType",
	"SerialNumber",
	"SocketDesignation",
	"ThreadCount",
	"InstallDate",
	"Family",
	"CurrentVoltage",
	"CpuStatus",
	"AddressWidth",
	"Architecture",
	"ErrorDescription"
}
			},
			{
				"Win32_SoundDevice",
{
	"Name",
	"Manufacturer",
	"MPU401Address",
	"InstallDate",
	"DeviceID",
	"PowerManagementSupported",
	"ProductName",
	"DMABufferSize",
	"Availability"
}
			},
			{
				"Win32_USBController",
{
	"Name",
	"Manufacturer",
	"InstallDate",
	"PowerManagementSupported",
	"ProtocolSupported",
	"MaxNumberControlled",
	"DeviceID",
	"Description",
	"Status",
	"ErrorDescription"
}
			},
			{
				"Win32_DesktopMonitor",
{
	"Name",
	"PowerManagementSupported",
	"ScreenWidth",
	"ScreenHeight",
	"PixelsPerYLogicalInch",
	"PixelsPerXLogicalInch",
	"MonitorManufacturer",
	"IsLocked",
	"DeviceID",
	"Description",
	"Availability"
}
			}
}
	}

};

int generateReport()
{
	SystemRat::WMIParser wmiParser{ globalMap };
	if (wmiParser.init())
	{
		return -1;
	}
	wmiParser.queryData();
	wmiParser.generateFile("report.json");
	return 0;
}